# Generated by Django 5.1 on 2026-03-03 06:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BucketList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('image', models.URLField(blank=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('category', models.CharField(blank=True, choices=[('one', 'One'), ('two', 'Two'), ('three', 'Three')], max_length=50, null=True)),
                ('is_open', models.BooleanField(default=True)),
                ('is_public', models.BooleanField(default=False)),
                ('has_deadline', models.BooleanField(default=False)),
                ('deadline', models.DateTimeField(blank=True, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_bucketlists', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BucketItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('image', models.URLField(blank=True, null=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_bucketitems', to=settings.AUTH_USER_MODEL)),
                ('bucket_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='bucketlists.bucketlist')),
            ],
        ),
        migrations.CreateModel(
            name='BucketListMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('contributor', 'Contributor'), ('viewer', 'Viewer')], default='contributor', max_length=20)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('bucket_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='bucketlists.bucketlist')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bucketlist_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('bucket_list', 'user')},
            },
        ),
        migrations.AddField(
            model_name='bucketlist',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='bucketlists', through='bucketlists.BucketListMember', to=settings.AUTH_USER_MODEL),
        ),
    ]
