# Generated by Django 5.1 on 2026-03-07 09:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bucketlists', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bucketlistmember',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='bucketlistmember',
            name='bucket_list',
        ),
        migrations.RemoveField(
            model_name='bucketlistmember',
            name='user',
        ),
        migrations.RemoveField(
            model_name='bucketlist',
            name='members',
        ),
        migrations.AlterModelOptions(
            name='bucketlist',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameField(
            model_name='bucketlist',
            old_name='date_created',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='bucketlist',
            old_name='deadline',
            new_name='decision_deadline',
        ),
        migrations.RemoveField(
            model_name='bucketlist',
            name='category',
        ),
        migrations.RemoveField(
            model_name='bucketlist',
            name='has_deadline',
        ),
        migrations.RemoveField(
            model_name='bucketlist',
            name='image',
        ),
        migrations.RemoveField(
            model_name='bucketlist',
            name='is_open',
        ),
        migrations.RemoveField(
            model_name='bucketlist',
            name='is_public',
        ),
        migrations.AddField(
            model_name='bucketlist',
            name='allow_viewer_voting',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bucketlist',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='BucketListInvite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('editor', 'Editor'), ('viewer', 'Viewer')], max_length=20)),
                ('token', models.CharField(editable=False, max_length=255, unique=True)),
                ('expires_at', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bucket_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invites', to='bucketlists.bucketlist')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='BucketListItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('proposed', 'Proposed'), ('locked_in', 'Locked_in'), ('complete', 'Complete'), ('cancelled', 'Cancelled')], default='proposed', max_length=20)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bucket_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='bucketlists.bucketlist')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_bucketlist_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BucketListMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('editor', 'Editor'), ('viewer', 'Viewer')], max_length=20)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('bucket_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='bucketlists.bucketlist')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bucketlist_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['joined_at'],
            },
        ),
        migrations.CreateModel(
            name='ItemVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote_type', models.CharField(choices=[('upvote', 'Upvote'), ('downvote', 'Downvote')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='bucketlists.bucketlistitem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_votes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.DeleteModel(
            name='BucketItem',
        ),
        migrations.DeleteModel(
            name='BucketListMember',
        ),
        migrations.AddConstraint(
            model_name='bucketlistinvite',
            constraint=models.UniqueConstraint(fields=('bucket_list', 'role'), name='unique_invite_role_per_bucket_list'),
        ),
        migrations.AddConstraint(
            model_name='bucketlistmembership',
            constraint=models.UniqueConstraint(fields=('bucket_list', 'user'), name='unique_membership_per_user_per_list'),
        ),
        migrations.AddConstraint(
            model_name='itemvote',
            constraint=models.UniqueConstraint(fields=('item', 'user'), name='unique_vote_per_user_per_item'),
        ),
    ]
