# Generated by Django 5.1 on 2026-03-08 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bucketlists', '0002_alter_bucketlistmember_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bucketlist',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
    ]
