# Generated by Django 5.1 on 2026-03-19 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bucketlists', '0005_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='is_dismissed',
            field=models.BooleanField(default=False),
        ),
    ]
