# Generated by Django 5.1 on 2026-03-21 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bucketlists', '0006_notification_is_dismissed'),
    ]

    operations = [
        migrations.AddField(
            model_name='bucketlist',
            name='is_frozen',
            field=models.BooleanField(default=False),
        ),
    ]
